services:
  web:
    image: nginx:latest
    ports:
      - "8000:80"
    volumes:
      - ./UnProjet:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - monreseau
    depends_on:
      - php

  php:
    build:
      context: ./php
      dockerfile: Dockerfile
    volumes:
      - ./UnProjet:/var/www/html
    depends_on:
      - db
    networks:
      - monreseau

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: UneBD
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - monreseau

volumes:
  db_data:

networks:
  monreseau:
    driver: bridge