version: '3.8'

services:
  php:
    build:
      context: ./php
      dockerfile: Dockerfile
    volumes:
      - ./UnProjet:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: UneBD
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

  web:
    image: nginx:latest
    ports:
      - "8000:80"
    volumes:
      - ./UnProjet:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

volumes:
  db_data: